services:
  app:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl
    environment:
      BACKEND_URL: ${BACKEND_URL}
      SERVER_NAME: ${SERVER_NAME}